---
  - name: Deploy new ansible control node from base Ubuntu install
    hosts: ansible
    become: yes
    strategy: free
    gather_facts: false
    vars_files: ~/ansible/secrets/ans_control_vars.yml

    tasks:
      - name: Update repo cache & full system update
        ansible.builtin.apt:
          update_cache: true
          upgrade: dist
          force_apt_get: true

      - name: Ensure dirmngr is installed
        ansible.builtin.apt:
          name: dirmngr
          state: present

      - name: Add ansible repository
        ansible.builtin.apt_repository:
          repo: 'ppa:ansible/ansible'
          update_cache: true

      - name: Install Ansible
        ansible.builtin.apt:
          name: ansible
          state: present

      - name: Install nfs-common
        ansible.builtin.apt:
          name: nfs-common
          state: present

      - name: Create backup dir (for backup automation)
        ansible.builtin.file:
          path: /mnt/backups
          state: directory
          mode: '0777'

      - name: Mount backup fileshare
        ansible.posix.mount:
          src: "{{ share_location }}:/volume1/backup_automation"
          path: /mnt/backups
          opts: defaults
          state: mounted
          fstype: nfs

      - name: Install git
        ansible.builtin.apt:
          name: git
          state: present

      - name: Create ansible dir
        ansible.builtin.file:
          path: /src/ansible-playbooks
          state: directory
          mode: '0777'

      - name: Clone this repository to pull in playbooks
        ansible.builtin.git:
          repo: https://github.com/btclay/ansible-playbooks.git
          dest: /src/ansible-playbooks
