---
  - name: Deploy new ansible control node from base Ubuntu install
    hosts: ansible
    become: yes
    strategy: free
    gather_facts: false

    tasks:

      - include_tasks: tasks/xenTenant.yml

      - name: Update repo cache & full system update
        ansible.builtin.apt:
          update_cache: true
          upgrade: dist
          force_apt_get: true

      - name: Ensure dirmngr is installed
        ansible.builtin.apt:
          name: dirmngr
          state: present

      - name: Add ansible repository
        ansible.builtin.apt_repository:
          repo: 'ppa:ansible/ansible'
          update_cache: true

      - name: Install Ansible
        ansible.builtin.apt:
          name: ansible
          state: present

      - name: Install nfs-common
        ansible.builtin.apt:
          name: nfs-common
          state: present

      - name: Install git
        ansible.builtin.apt:
          name: git
          state: present

      - name: Create ansible dir
        become: false
        ansible.builtin.file:
          path: ~/ansible/playbooks
          state: directory

      - name: Clone this repository to pull in playbooks
        become: false
        ansible.builtin.git:
          repo: https://github.com/btclay/ansible-playbooks.git
          dest: ~/ansible/playbooks
