services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: /docker/uptime-kuma/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - uptime-kuma
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - /docker/uptime-kuma/data:/app/data
    restart: unless-stopped
